### ISSUE TITLE
Switch to other app and switch back, get a blank screen

### ISSUE THREAD

**Issue by linsui** [Flowit-Game/Flowit#18]
If I switch to another app or home screen, then when I enter this app I'll get a blank screen. Could you please take a look? Thanks!

**Comment by friendly-user-t** [comment]
It happens as well, if the screen locks while playing (i.e. when thinking takes some time). If you unlock it again, a white screen appears which only disappears if you restart the app.

Tested on both Pixel 6 with latest Stock Android and Pixel 4a 5G running latest CalyxOS.

**Comment by cweiske** [comment]
Happens here on Wileyfox swith with LineageOS 17.1.
