### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by markcjf** [Flowit-Game/Flowit#21]
So, great game - my grandchild loves the easy, he is 9 but smallish issue with game.
When I leave app to open any other apps and then return to game I have to close and reopen as each time I get a white screen as shown in image.

I have android, galaxy s20 
![Screenshot_20220609-150606_Flowit!](https://user-images.githubusercontent.com/19439398/172867345-2d26da86-e7b3-4297-8a98-1b31d11c7b27.jpg)

For your info/action

**Comment by cweiske** [comment]
This is a duplicate of #18.

**Comment by markcjf** [comment]
Copy of #18 so as requested closed
