### ISSUE TITLE
restore completed levels from older phone

### ISSUE THREAD

**Issue by iltommi** [Flowit-Game/Flowit#23]
is it possible?
Which file stores the completed levels?

Thanks a million

**Comment by ByteHamster** [comment]
Unfortunately, this is currently not possible

**Comment by vertigo220** [comment]
@ByteHamster Why is this not possible? Many other apps/games can do this. I consider this crucial functionality for most games, especially one like this where it can take a long time to progress through it and levels have to be unlocked to play later ones, so switching devices can result in a massive loss of progress/time. In fact, I've had this happen so many times I've reached the point I often won't even bother with games like this anymore unless they're particularly good.
