### ISSUE TITLE
Community level sorting

### ISSUE THREAD

**Issue by comradekingu** [Flowit-Game/Flowit#24]
Just played through the community levels.

Community level 3 is harder than nr. 3.
Something is wrong with nr. 10?
Nr. 11 is also just pretending to be difficult.
12 and 13 are also exceedingly easy…
Nr 8 is harder than its placement.

Nr 15 was a good finisher.

Forgot to do this for the other levels.

37 easy is unsolved for me.

6 9 12 14 15 17 18 19 21 and 22 hard are also unsolved for me

**Comment by ByteHamster** [comment]
Community levels don't have any order. Otherweise, new levels would appear between already solved levels when someone suggests a new level

**Comment by comradekingu** [comment]
@ByteHamster 
If the other levels are sorted by difficulty, and that works well, my assumption is that these will be too.
I will know it is new because it gets added a list of all cleared levels (all of which are currently quite easy).
If I don't have any cleared levels, or not enough to where I would notice, what difference does it make?

Whereas, if it is new _and positioned_, I can also gauge how difficult it is going to be, like with the other levels.

The list isn't scrolling, so nothing will be missed, and most people haven't played this game.
