### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [Flowit-Game/Flowit#28]
https://monitor.f-droid.org/builds/log/com.bytehamster.flowitgame/304#site-footer

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/vagrant/build/com.bytehamster.flowitgame/app/build.gradle' line: 61

* What went wrong:
Execution failed for task ':app:compressLevelFile'.
> java.io.FileNotFoundException: /home/vagrant/build/com.bytehamster.flowitgame/app/src/main/assets/levelsEasy.xml (No such file or directory)
```

Could you please take a look? Thanks!

**Comment by linsui** [comment]
By the way, I'm going to remove the summaries from fdroiddata repo in favour the fastlane data in your repo. You can add them to your repo. See https://gitlab.com/fdroid/fdroiddata/-/tree/4d9cf75a82358285397f6932d7ca457ee1b2c025/metadata/com.ulicae.cinelog

**Comment by ByteHamster** [comment]
The repo needs to be cloned with submodules

**Comment by linsui** [comment]
Thanks!
