### ISSUE TITLE
Feature request: Hints

### ISSUE THREAD

**Issue by d4f5409d** [Flowit-Game/Flowit#29]
Have hints when you can't solve a puzzle

**Comment by soam1** [comment]
Please Let me work on it, I will provide the best possible commit.
I hope you will assign the issue to me

**Comment by ByteHamster** [comment]
How do you imagine the hints to work? Where would you get the data from?

**Comment by ByteHamster** [comment]
After working on an optimal level solver for some time, I don't think this feature is possible. It sometimes takes my computer 2 hours of time and 25GB of RAM to solve a level. That's not something that could be done on-the-fly on a phone
