### ISSUE TITLE
Main Screen empty on opening

### ISSUE THREAD

**Issue by rsiccho** [Flowit-Game/Flowit#3]
Hi,
When I open the app, the main screen is empty. Only the grey background is painted. The buttons are there and clickable but not visible. (no Label, not blue painted)
Going back to the app drawer or the view with the last opened apps and clicking on FlowIt again shows the menu.

Device: LG G8s
Android 10

Thanks for making the game, I love it!

**Comment by A-Nicoladie** [comment]
I have the same problem. See below a capture of what's happening.

<img src="https://user-images.githubusercontent.com/90625228/147097344-77f3c244-7344-46ed-8272-122481abc3b8.gif" width="200" />

**Comment by Moonbood** [comment]
I have an empty screen on start. In my opinion has the app a problem with a locked screen caused by inactivity / energy saving mode.

I like the gameplay. Thank you for programming!

**Comment by Moonbood** [comment]
The workaround works for me:
Minimize the app and tap the game icon new.

**Comment by adolfintel** [comment]
Same problem here, @Moonbood's workaround works

**Comment by Szuwax** [comment]
I have the same problem. Workaround mentioned above  works.

**Comment by ByteHamster** [comment]
Someone posted a duplicate and the duplicate has more thumbs-up, so I will close the original instead of the duplicate
