### ISSUE TITLE
Possibly incorrect author name in community levels 158

### ISSUE THREAD

**Issue by ywnico** [Flowit-Game/Flowit#35]
In `levelsCommunity.xml`, level 158 has author "Perkuson", while several other levels have author "Perkuon". I'm guessing this is a typo, although maybe not (perhaps Perkuson is the son of Perkuon?)

**Comment by ByteHamster** [comment]
Yeah, I guess it's a typo, but that's the name that was entered in the level editor. The person did not leave an email address, so we can't ask them.

**Comment by ywnico** [comment]
Sorry I never responded here. Indeed, I guess there's no solution....if it is the same person, they should have typed their name more carefully.
