### ISSUE TITLE
Add details on the menu screen

### ISSUE THREAD

**Issue by A-Nicoladie** [Flowit-Game/Flowit#4]
Hi !
Is it possible to consider adding some information on the menus:

- Display the best score achieved for each level
- Display for each level a reward (star, medal...) when the number of moves done is equal to the minimum
- Add the number of reward get for each difficulty 

Thanks for this good game :+1:

**Comment by ByteHamster** [comment]
It now shows the minimum and a star if you solved the minimum (for most levels where we know the minimum)
