### ISSUE TITLE
Level 35 of medium difficulty is imposible.

### ISSUE THREAD

**Issue by fedegallar** [Flowit-Game/Flowit#41]
I've tried for days to complete level 35 of medium difficulty without success. I have downloaded the f-droid version.

https://github.com/Flowit-Game/Flowit/assets/7192533/c087473e-bdac-4227-a1cf-a25df175d2f4

I don't know if it's something with the puzzle or is my lack of intelligence to solve the puzzle 😔

**Comment by ByteHamster** [comment]
All levels can definitely be solved ;) For this level, do not remove the green box in the bottom left, only the one in the top.
