### ISSUE TITLE
Does community level 38 have a solution?

### ISSUE THREAD

**Issue by anfourny** [Flowit-Game/Flowit#42]
I have all levels solved except for this one. There is a blue square in the center of the board that I don't see how to fill. 

I'm wondering if the green bomb should be one square higher? Otherwise it overwrites the blue square and I don't see how it can be solved.
![Screenshot_20240803_131905_Flowit!](https://github.com/user-attachments/assets/82152076-e606-488d-98d6-fcc309689e2d)

**Comment by ByteHamster** [comment]
Of course it has a solution :) You don't actually need the bomb. It is possible to solve the level by just clicking the bomb in the very first step and removing all the boxes it filled

**Comment by anfourny** [comment]
Oh thanks, I finally got it!!!
